### ISSUE TITLE
Wrong method?

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/skript-reflect#61] opened 2022-12-23 18:26 UTC
**Describe the bug**
`#args()` method returns single `TranslatableComponent` instead of `List<Component>`

**To reproduce**
```
import:
    org.bukkit.event.player.PlayerAdvancementDoneEvent

    net.kyori.adventure.text.format.NamedTextColor

    net.kyori.adventure.text.serializer.gson.GsonComponentSerializer

    net.kyori.adventure.text.TranslatableComponent

    java.lang.Class

on PlayerAdvancementDoneEvent:
    set {_message} to event.message()
    set {_args} to {_message}.args()
    send "args %{_args}%" to (ops and console)
```

**Expected behavior**
`#args()` method to return List

**Screenshots**
![image](https://user-images.githubusercontent.com/59025999/209391479-a458e771-72da-427a-b342-c81f6040e798.png)

**Server information**
- skript-reflect: 2.3
- Skript: 2.6.4
- Bukkit: purpur-1876 (1.19.3)
- Minecraft: 1.19.3
- Java: 17
- OS: CentOS 7

**Additional context**
I've tried with `[TranslatableComponent]args()` too

**Comment by TPGamesNL** [comment] 2022-12-24 09:39
Issue is caused by these methods:
![image](https://user-images.githubusercontent.com/29547183/209429403-c5004fec-e62f-420c-a618-7b2551d62071.png)
Since the second is a varargs method, `{_var}.args()` is also a valid call for that method.

Fixed in https://github.com/TPGamesNL/skript-reflect/commit/8f6bb82950906489a5e382efef04f82690ea757e by prioritizing non-varargs methods.

If anyone has this situation (two methods with same signature apart from varargs) and wants to use the varargs one instead, use either argument specification (e.g. `{-msg}.args[ComponentLike[]]()`) or specify a zero-length array in the method (e.g. `{-msg}.args(new ComponentLike[0])`)

**Closed as completed by TPGamesNL** 2022-12-24 09:39 UTC
