### ISSUE TITLE
Custom events is extremely slow

### ISSUE THREAD

**Issue by Lotzyprod** [SkriptLang/skript-reflect#89] opened 2024-01-27 23:43 UTC
**Describe the bug**
With new skript-reflect using custom events is extremely slow.
I'll tested same script for listening packets on Skript 2.6.4 + Skript-reflect 2.3 and Skript 2.8 + Skript-reflect 2.4
Event calling on 2.6.4: average 0.5356ms
Event calling on 2.8:  average 26.2471ms  (range from 5ms to 100ms)

**To reproduce**
[Script here](https://pastebin.com/42yFNfAa). You can run this on any of specified by me versions of skript and reflect.
I think its something related to sections api update. Something broken as broken parse section.

**Additional info**
lines 609 - 613  is custom event
line 615 - handling event
lines 549,590, 599 event calling

**Server information**
- skript-reflect: 2.4
- Skript: 2.8

- Skript: 2.6.4
- skript-reflect 2.3

- Bukkit: 1.20.4

**Comment by Lotzyprod** [comment] 2024-01-31 13:25
After many tests, it turned out that in general, event processing in Skript has slowed down. I recreated similar code in Java and implemented a Bukkit event related to this. Then I registered the event in Skript.
Calling an event via import in Skript-reflect does not cause any problems.
While using a registered event produces a similar problem as described above.

Can someone move this issue to Skript repo

**Comment by sovdeeth** [comment] 2024-01-31 14:54
> After many tests, it turned out that in general, event processing in Skript has slowed down. I recreated similar code in Java and implemented a Bukkit event related to this. Then I registered the event in Skript. Calling an event via import in Skript-reflect does not cause any problems. While using a registered event produces a similar problem as described above.
> 
> Can someone move this issue to Skript repo

You should open a new issue there with the relevant information, like a way to reproduce. Moving this issue wouldn't be very useful since all the information is for skript-reflect.

**Comment by sovdeeth** [comment] 2024-01-31 18:42
This appears to just be a misunderstanding of how Skript handles async events.

**Closed as not planned by sovdeeth** 2024-01-31 18:42 UTC
