### ISSUE TITLE
Error when using integers/numbers in custom events

### ISSUE THREAD

**Issue by Palgia** [SkriptLang/skript-reflect#107] opened 2024-05-08 00:25 UTC
**Describe the bug**
Using number and integer in custom events with multiple event-values can throw the following error when the server is loading another skript which use the event:
"There's no integer in an on custom event event" (Yes, "event" is written two times)

Removing the number/integer from the event and the skript using the event removes the error. 

**To reproduce**
- Create an event with some event-values, which one of them are an integer or a number. (I'm using player, string, integer)
- Call the event in another skript
- Restart the server

**Expected behavior**
I expected my event to be parsed without errors.

**Screenshots**
I don't have any screenshot, the error is described above.

**Server information**
- skript-reflect: 2.4
- Skript: 2.8.3
- Bukkit: git-Paper-496
- Minecraft: 1.20.4
- Java: 21
- OS: Linux

**Additional context**
No context.

**Comment by sovdeeth** [comment] 2024-05-08 00:29
Does this version fix your issue?
[skript-reflect-2.4-nightly.zip](https://github.com/SkriptLang/skript-reflect/files/15242397/skript-reflect-2.4-nightly.zip)

**Comment by Palgia** [comment] 2024-05-08 00:39
Yes! No errors and it works fine in game. 

I'm making a quest skript. When my resource is published, can I indicate to players to download this specific version for my script to work, or are there any instabilities to know?

**Comment by sovdeeth** [comment] 2024-05-08 00:45
No, it's exactly what you'd get if you built the main branch of reflect right now
We do need to put out a 2.4.1 or whatever

**Comment by sovdeeth** [comment] 2024-05-08 00:45
Closing as duplicate of #91

**Closed as completed by sovdeeth** 2024-05-08 00:45 UTC
Labels: waiting for reply, investigating
