### ISSUE TITLE
cannot load scripts with command

### ISSUE THREAD

**Issue by ChoonSik21** [SkriptLang/skript-reflect#101] opened 2024-04-05 15:16 UTC
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! [Skript] Severe Error:
[00:12:21 ERROR]: #!#! Exception occurred in Skript's main command
[00:12:21 ERROR]: #!#! Used command: /sk reload scripts
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! Something went horribly wrong with Skript.
[00:12:21 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:12:21 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:12:21 ERROR]: #!#! Here is full list of them:
[00:12:21 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) ItemsAdder v3.6.3-beta-13 (devs.beer) SkBee v3.4.3 (https://github.com/ShaneBeee/SkBee) skUtilities v0.9.2 (https://tim740.github.io/) skript-yaml v1.5 Skellett v2.0.10 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.10 DiscordSRV v1.27.0 (https://github.com/DiscordSRV/DiscordSRV)
[00:12:21 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:12:21 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:12:21 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:12:21 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:12:21 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:12:21 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! Stack trace:
[00:12:21 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "java.util.Map.remove(Object)" because "syntaxes" is null
[00:12:21 ERROR]: #!#!     at skript-reflect-2.4.jar//org.skriptlang.reflect.syntax.CustomSyntaxStructure.lambda$unload$1(CustomSyntaxStructure.java:158)
[00:12:21 ERROR]: #!#!     at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[00:12:21 ERROR]: #!#!     at skript-reflect-2.4.jar//org.skriptlang.reflect.syntax.CustomSyntaxStructure.unload(CustomSyntaxStructure.java:153)
[00:12:21 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:830)
[00:12:21 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:152)
[00:12:21 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:12:21 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[00:12:21 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:1005)
[00:12:21 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:990)
[00:12:21 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:540)
[00:12:21 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[00:12:21 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[00:12:21 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[00:12:21 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[00:12:21 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! Version Information:
[00:12:21 ERROR]: #!#!   Skript: 2.8.4 (latest)
[00:12:21 ERROR]: #!#!     Flavor: skriptlang-github
[00:12:21 ERROR]: #!#!     Date: 11:03:52.948789700
[00:12:21 ERROR]: #!#!   Bukkit: 1.20.2-R0.1-SNAPSHOT
[00:12:21 ERROR]: #!#!   Minecraft: 1.20.2
[00:12:21 ERROR]: #!#!   Java: 17.0.8 (OpenJDK 64-Bit Server VM 17.0.8+7)
[00:12:21 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! Server platform: Paper
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! Current node: null
[00:12:21 ERROR]: #!#! Current item: null
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! Thread: Server thread
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! Language: korean
[00:12:21 ERROR]: #!#! Link parse mode: DISABLED
[00:12:21 ERROR]: #!#!
[00:12:21 ERROR]: #!#! End of Error.
[00:12:21 ERROR]: #!#!

**Comment by larpxenon** [comment] 2024-04-05 15:27
Skrip reflect is the problem

**Comment by Moderocky** [comment] 2024-04-05 15:41
Whoops thought this was the Skript repo, was about to send you here haha

**Comment by Moderocky** [comment] 2024-04-05 15:42
What were you doing when this issue occurred?

**Comment by AyhamAl-Ali** [comment] 2024-04-05 15:57
Hello :wave: this is a duplicate of #86

**Closed as not planned by AyhamAl-Ali** 2024-04-05 15:57 UTC
Labels: duplicate
